### ISSUE TITLE
Request a 1Password account for the cert-manager project?

### ISSUE THREAD

**Issue by maelvls** [cert-manager/infrastructure#30]
Up to now, we have been using Jetstack's and then Venafi's 1Password to store the various passwords for the shared accounts, such as:

- Netlify,
- ArtifactHub,
- the Zoom account that the CNCF pays for,
- Zapier,
- Twitter,
- Mastodon.

A while back, we had written in https://github.com/cert-manager/infrastructure/blob/main/README.md#google-groups-cert-manager-maintainers:

> [cert-manager-maintainers](https://groups.google.com/g/cert-manager-maintainers) is the ultimate decider of who's a recognised maintainer. All other memberships should be based off this group, and if a maintainer retires from the project, they should be removed from this group. There should be automation added to ensure that members of this group are: able to access any secrets they need (e.g. login credentials)

What if we were to ~[request an open source team](https://github.com/1Password/1password-teams-open-source) from 1Password~ request a CNCF-paid 1Password team?

**Internal ref:** https://venafi.atlassian.net/browse/VC-33449

To to:

- [x] Request the 1password team using CNCF's service desk.
- [x] Document the process for onboarding maintainers in https://github.com/cert-manager/infrastructure's readme. → https://github.com/cert-manager/infrastructure/pull/45

**Comment by SgtCoDFish** [comment]
We discussed this today and agreed we'd try to use the CNCF 1password offering: https://contribute.cncf.io/resources/project-services/hosted-tools/

This is Maël's task now, we've agreed to proceed with this!

**Comment by SgtCoDFish** [comment]
NOTE: We'll also need to update the [readme](https://github.com/cert-manager/infrastructure?tab=readme-ov-file#important-note-credentials) in this repo since it currently talks about credentials being in 1password

**Comment by maelvls** [comment]
I’ve sent the request for a 1Password team: [CNCFSD-2290](https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-2290).

**Comment by maelvls** [comment]
I haven't heard back yet. I'll keep you updated here.

**Comment by maelvls** [comment]
From Daniel Krook:

> Hi. We don’t handle 1Password on behalf of projects, but we point folks to where they can apply for accounts: https://github.com/1Password/for-open-source

I guess I'll have to use 1Password's free open source team then 😅

**Comment by maelvls** [comment]
I've created the team https://cert-manager.1password.com and invited all 9 maintainers using the emails visible in https://groups.google.com/g/cert-manager-maintainers/members (is that the maintainers' canonical email addresses?)

FYI @cert-manager/milestone-maintainers

**Comment by maelvls** [comment]
All done!

Last step is to document the onboarding/offboarding of maintainers. I'll add that to the [adam onboarding checklist](https://github.com/cert-manager/community/pull/23#issuecomment-2097794815) so that I don't forget.

**Comment by maelvls** [comment]
I've written the docs about the new 1Password team in https://github.com/cert-manager/infrastructure/pull/45. Closing now.
