### ISSUE TITLE
Immutable Docker image tags

### ISSUE THREAD

**Issue by sathieu** [cert-manager/infrastructure#31]
Image for [quay.io/jetstack/cert-manager-package-debian:20210119.0](https://quay.io/repository/jetstack/cert-manager-package-debian?tab=tags&tag=latest) recently changed digest.

This is a good practice to use immutable tags (i.e. same digest), and create new tags when there is a new release. This allows to use tools like renovate or dependabot to secure image retrieval.

Thanks :pray:

**Comment by inteon** [comment]
@SgtCoDFish

**Comment by SgtCoDFish** [comment]
We can consider making this our policy, but there are also drawbacks to adopting this. Most notably, every single trust-manager Helm chart which supports this image points at that tag. Bumping the version would force us to release a new chart for every supported trust-manager release.

I'd like to get to a point where all tags are immutable. Maybe should be a goal for v1 - I'll add to the milestone in trust-manager.

**Comment by SgtCoDFish** [comment]
I raised https://github.com/cert-manager/trust-manager/issues/328 to track this in the trust-manager repo. I'll close this one in favour of that.

Thanks for raising this 🚀
