### ISSUE TITLE
Release 1.15.0-alpha.0 failed due to "Cannot insert legacy ACL for an object when uniform bucket-level access is enabled"

### ISSUE THREAD

**Issue by maelvls** [cert-manager/infrastructure#33]
While releasing 1.15.0-alpha.0, the Google Cloud Build that ran after I pushed the tag [failed](https://console.cloud.google.com/cloud-build/builds;region=global/0514a4bb-d295-4eca-a9dd-ba9f0a0643be?project=cert-manager-release):

> Step #1: 2024/03/29 09:13:51 ERROR : cert-manager-manifests.tar.gz: Failed to copy: googleapi: Error 400: Cannot insert legacy ACL for an object when uniform bucket-level access is enabled. Read more at https://cloud.google.com/storage/docs/uniform-bucket-level-access, invalid

I was able to reproduce the error message with the following command:

```console
$ gsutil acl get gs://cert-manager-release
BadRequestException: 400 Cannot get legacy ACL for a bucket that has uniform bucket-level access. Read more at https://cloud.google.com/storage/docs/uniform-bucket-level-access
```

This issue may have appeared when we migrated everything... maybe. The bucket is defined as:

```tf
module "trusted-artifacts-bucket" {
  source = "./modules/gcp-bucket/"

  project_id  = module.cert-manager-tests-trusted.project_id
  location    = local.bucket_location
  bucket_name = "cert-manager-prow-artifacts"

  bucket_prevent_public_access = false
  bucket_viewers = [
    "allUsers"
  ]
  bucket_admins = [
    google_service_account.prow-gcs-publisher.member
  ]
}
```

I'll keep you updated here.

**Comment by inteon** [comment]
@maelvls I reverted the bucket permissions to ACL in the UI to make this work again.
Next week, we can figure out if we want to keep using ACL or fix the upload command instead.
