### ISSUE TITLE
Final steps migration to CNCF infrastructure

### ISSUE THREAD

**Issue by inteon** [cert-manager/infrastructure#44]
This issue tracks the progress of the migration to CNCF infrastructure.

- [x] moved the GCP `cert-manager-release` project to the CNCF GCP organisation
- [x] clean-room deploy of cert-manager testing infrastructure in new GCP projects
- [x] bug and stability fixes
- [x] via CNCF service desk: point registar to new CloudDNS instances on GCP
- [x] install triage-party tool
- [x] migrate Netlify
- [x] tear-down old testing infrastructure (https://github.com/jetstack/terraform-jetstack-build-infra/pull/36)

**Comment by maelvls** [comment]
Can we close this ticket? Or do we still need to do something? I think we have decided we want to continue using http://triage.infra.cert-manager.io/

**Comment by inteon** [comment]
The migration has been completed (ofc. further improvements are possible and desirable, but will be tracked separately). 🥳

**Comment by maelvls** [comment]
Hey, about the migration of the Kubernetes clusters, is the documentation up to date regarding the Kubernetes name and GCP project name, e.g., in https://github.com/cert-manager/testing/tree/master/prow?
